//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACE_ACESSO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACE_ACESSO()
        {
            this.PES_PESSOA = new HashSet<PES_PESSOA>();
        }
    
        public int ISN_ACESSO { get; set; }
        public string TIP_ACESSO { get; set; }
        public string DSC_ACESSO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PES_PESSOA> PES_PESSOA { get; set; }
    }
}
namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANI_ANEXO_NINHADA
    {
        public int ISN_ANEXO_NINHADA { get; set; }
        public Nullable<int> ISN_NINHADA { get; set; }
        public string NOM_ANEXO_NINHADA { get; set; }
        public string NOM_ANEXO_FISICO { get; set; }
    
        public virtual NIN_NINHADA NIN_NINHADA { get; set; }
    }
}
namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATR_ANEXO_TRANSFERENCIA
    {
        public int ISN_ANEXO_TRANSFERENCIA { get; set; }
        public Nullable<int> ISN_TRANSFERENCIA { get; set; }
        public string NOM_ANEXO_TRANSFERENCIA { get; set; }
        public string NOM_ANEXO_FISICO { get; set; }
    
        public virtual TRA_TRANSFERENCIA TRA_TRANSFERENCIA { get; set; }
    }
}
namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAN_BANDEIRA
    {
        public int ISN_BANDEIRA { get; set; }
        public string DSC_BANDEIRA { get; set; }
    }
}
namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAN_CANIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAN_CANIL()
        {
            this.PES_PESSOA = new HashSet<PES_PESSOA>();
        }
    
        public int ISN_CANIL { get; set; }
        public string CODIGO_FCI { get; set; }
        public string NOME { get; set; }
        public Nullable<int> ISN_CLUBE { get; set; }
        public string PROPRIETARIO { get; set; }
        public string COPROPRIETARIO { get; set; }
        public Nullable<System.DateTime> ANUIDADE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PES_PESSOA> PES_PESSOA { get; set; }
        public virtual CLB_CLUBE CLB_CLUBE { get; set; }
    }
}
namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAR_CARRINHO
    {
        public int ISN_CARRINHO { get; set; }
        public int ISN_SOLICITACAO { get; set; }
        public int ISN_PESSOA { get; set; }
    
        public virtual PES_PESSOA PES_PESSOA { get; set; }
        public virtual SOL_SOLICITACAO SOL_SOLICITACAO { get; set; }
    }
}
namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class CID_CIDADE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CID_CIDADE()
        {
            this.CLB_CLUBE = new HashSet<CLB_CLUBE>();
            this.PES_PESSOA = new HashSet<PES_PESSOA>();
        }
    
        public int ISN_CIDADE { get; set; }
        public string DSC_CIDADE { get; set; }
        public Nullable<int> ISN_ESTADO { get; set; }
    
        public virtual EST_ESTADO EST_ESTADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLB_CLUBE> CLB_CLUBE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PES_PESSOA> PES_PESSOA { get; set; }
    }
}
namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLB_CLUBE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLB_CLUBE()
        {
            this.PES_PESSOA = new HashSet<PES_PESSOA>();
            this.CAN_CANIL = new HashSet<CAN_CANIL>();
        }
    
        public int ISN_CLUBE { get; set; }
        public string DSC_CLUBE { get; set; }
        public Nullable<int> ISN_ESTADO { get; set; }
        public Nullable<int> ISN_REGIAO { get; set; }
        public string DSC_ENDERECO { get; set; }
        public string NUM_CEP { get; set; }
        public string NUM_TELEFONE_1 { get; set; }
        public string NUM_TELEFONE_2 { get; set; }
        public string DSC_EMAIL { get; set; }
        public string DSC_SITE { get; set; }
        public string NOM_CIDADE { get; set; }
        public string DSC_BAIRRO { get; set; }
        public Nullable<int> ISN_CIDADE { get; set; }
        public Nullable<int> STA_ADESAO { get; set; }
        public string DSC_SIGLACLUBE { get; set; }
    
        public virtual EST_ESTADO EST_ESTADO { get; set; }
        public virtual REG_REGIAO REG_REGIAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PES_PESSOA> PES_PESSOA { get; set; }
        public virtual CID_CIDADE CID_CIDADE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAN_CANIL> CAN_CANIL { get; set; }
    }
}
namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRC_COR_RACA
    {
        public int ISN_COR_RACA { get; set; }
        public string DSC_COR_RACA { get; set; }
        public Nullable<int> ISN_RACA { get; set; }
        public Nullable<int> ISN_VARIEDADE_RACA { get; set; }
    
        public virtual RAC_RACA RAC_RACA { get; set; }
        public virtual VAR_VARIEDADE_RACA VAR_VARIEDADE_RACA { get; set; }
    }
}
namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUP_CUPOM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUP_CUPOM()
        {
            this.FAT_FATURA = new HashSet<FAT_FATURA>();
        }
    
        public int ISN_CUPOM { get; set; }
        public string COD_CUPOM { get; set; }
        public Nullable<decimal> VLR_CUPOM { get; set; }
        public Nullable<int> ISN_PESSOA_REEMBOLSO { get; set; }
        public string NOM_PESSOA_REEMBOLSO { get; set; }
        public Nullable<int> ISN_PESSOA_CADASTRO_CUPOM { get; set; }
        public string NOM_PESSOA_CADASTRO_CUPOM { get; set; }
        public Nullable<System.DateTime> DAT_CADASTRO { get; set; }
        public Nullable<System.DateTime> DAT_UTILIZACAO { get; set; }
        public Nullable<int> ISN_SOLICITACAO { get; set; }
        public Nullable<byte> STA_CUPOM { get; set; }
    
        public virtual PES_PESSOA PES_PESSOA { get; set; }
        public virtual PES_PESSOA PES_PESSOA1 { get; set; }
        public virtual SOL_SOLICITACAO SOL_SOLICITACAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAT_FATURA> FAT_FATURA { get; set; }
    }
}
namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAR_DOMINIO_ATRIBUTO
    {
        public string NOM_ATRIBUTO { get; set; }
        public byte VAL_ATRIBUTO { get; set; }
        public string DES_ATRIBUTO { get; set; }
        public string NUM_ATRIBUTO_COR { get; set; }
    }
}
namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class EST_ESTADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EST_ESTADO()
        {
            this.CLB_CLUBE = new HashSet<CLB_CLUBE>();
            this.PES_PESSOA = new HashSet<PES_PESSOA>();
            this.CID_CIDADE = new HashSet<CID_CIDADE>();
        }
    
        public int ISN_ESTADO { get; set; }
        public string DSC_ESTADO { get; set; }
        public Nullable<int> ISN_REGIAO { get; set; }
        public string SIGLA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLB_CLUBE> CLB_CLUBE { get; set; }
        public virtual REG_REGIAO REG_REGIAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PES_PESSOA> PES_PESSOA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CID_CIDADE> CID_CIDADE { get; set; }
    }
}
namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAT_FATURA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FAT_FATURA()
        {
            this.ITF_ITEM_FATURA = new HashSet<ITF_ITEM_FATURA>();
        }
    
        public int ISN_FATURA { get; set; }
        public Nullable<int> ISN_PESSOA { get; set; }
        public string DSC_FORMA_PAGTO { get; set; }
        public Nullable<decimal> VLR_FATURA { get; set; }
        public Nullable<int> QTDE_PARCELAS { get; set; }
        public Nullable<int> ISN_SOLICITACAO { get; set; }
        public Nullable<int> ISN_CUPOM { get; set; }
        public Nullable<decimal> VLR_TAXA { get; set; }
        public Nullable<decimal> VLR_CUPOM { get; set; }
        public Nullable<System.DateTime> DAT_FATURA { get; set; }
    
        public virtual PES_PESSOA PES_PESSOA { get; set; }
        public virtual SOL_SOLICITACAO SOL_SOLICITACAO { get; set; }
        public virtual CUP_CUPOM CUP_CUPOM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITF_ITEM_FATURA> ITF_ITEM_FATURA { get; set; }
    }
}
namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIL_FILHOTE
    {
        public int ISN_FILHOTE { get; set; }
        public Nullable<int> ISN_NINHADA { get; set; }
        public string NOM_FILHOTE { get; set; }
        public string SEXO { get; set; }
        public Nullable<int> ISN_COR { get; set; }
        public Nullable<int> ISN_VARIEDADE_RACA { get; set; }
        public string NUM_MICROCHIP { get; set; }
    
        public virtual NIN_NINHADA NIN_NINHADA { get; set; }
        public virtual VAR_VARIEDADE_RACA VAR_VARIEDADE_RACA { get; set; }
    }
}
namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITF_ITEM_FATURA
    {
        public int ISN_ITEM_FATURA { get; set; }
        public Nullable<int> ISN_FATURA { get; set; }
        public Nullable<int> ISN_SOLICITACAO { get; set; }
        public Nullable<decimal> VLR_SOLICITACAO { get; set; }
    
        public virtual FAT_FATURA FAT_FATURA { get; set; }
        public virtual SOL_SOLICITACAO SOL_SOLICITACAO { get; set; }
    }
}
namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class NIN_NINHADA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NIN_NINHADA()
        {
            this.FIL_FILHOTE = new HashSet<FIL_FILHOTE>();
            this.ANI_ANEXO_NINHADA = new HashSet<ANI_ANEXO_NINHADA>();
            this.SOL_SOLICITACAO = new HashSet<SOL_SOLICITACAO>();
        }
    
        public int ISN_NINHADA { get; set; }
        public Nullable<System.DateTime> DAT_NASCIMENTO { get; set; }
        public Nullable<int> ISN_RACA { get; set; }
        public string NOM_PAI { get; set; }
        public string RG_PAI { get; set; }
        public string NOM_MAE { get; set; }
        public string RG_MAE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIL_FILHOTE> FIL_FILHOTE { get; set; }
        public virtual RAC_RACA RAC_RACA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANI_ANEXO_NINHADA> ANI_ANEXO_NINHADA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOL_SOLICITACAO> SOL_SOLICITACAO { get; set; }
    }
}
namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPG_OPCAO_PAGAMENTO
    {
        public int ISN_OPCAO_PAGAMENTO { get; set; }
        public string DSC_OPCAO_PAGAMENTO { get; set; }
    }
}
namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class PES_PESSOA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PES_PESSOA()
        {
            this.SOL_SOLICITACAO = new HashSet<SOL_SOLICITACAO>();
            this.FAT_FATURA = new HashSet<FAT_FATURA>();
            this.CAR_CARRINHO = new HashSet<CAR_CARRINHO>();
            this.CUP_CUPOM = new HashSet<CUP_CUPOM>();
            this.CUP_CUPOM1 = new HashSet<CUP_CUPOM>();
        }
    
        public int ISN_PESSOA { get; set; }
        public string NOM_PESSOA { get; set; }
        public string DSC_EMAIL { get; set; }
        public string CPF { get; set; }
        public string RG { get; set; }
        public string DSC_ENDERECO { get; set; }
        public Nullable<int> ISN_CLUBE { get; set; }
        public Nullable<int> ISN_CANIL { get; set; }
        public string NOM_CANIL { get; set; }
        public Nullable<int> ISN_ESTADO { get; set; }
        public Nullable<int> ISN_ACESSO { get; set; }
        public string DSC_CIDADE { get; set; }
        public string DSC_SENHA { get; set; }
        public string NUM_CEP { get; set; }
        public string DSC_COMPLEMENTO { get; set; }
        public Nullable<int> ISN_CIDADE { get; set; }
        public string DSC_BAIRRO { get; set; }
    
        public virtual CLB_CLUBE CLB_CLUBE { get; set; }
        public virtual EST_ESTADO EST_ESTADO { get; set; }
        public virtual ACE_ACESSO ACE_ACESSO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOL_SOLICITACAO> SOL_SOLICITACAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAT_FATURA> FAT_FATURA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAR_CARRINHO> CAR_CARRINHO { get; set; }
        public virtual CID_CIDADE CID_CIDADE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUP_CUPOM> CUP_CUPOM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUP_CUPOM> CUP_CUPOM1 { get; set; }
        public virtual CAN_CANIL CAN_CANIL { get; set; }
    }
}
namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRD_PARAMETRO_DESCONTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRD_PARAMETRO_DESCONTO()
        {
            this.RAC_RACA = new HashSet<RAC_RACA>();
        }
    
        public int ISN_PARAMETRO { get; set; }
        public string DSC_PARAMETRO { get; set; }
        public Nullable<decimal> PERCENTUAL_DESCONTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RAC_RACA> RAC_RACA { get; set; }
    }
}
namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRS_PRECO_SERVICO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRS_PRECO_SERVICO()
        {
            this.SER_SERVICO = new HashSet<SER_SERVICO>();
        }
    
        public int ISN_PRECO_SERVICO { get; set; }
        public Nullable<decimal> VLR_SERVICO { get; set; }
        public Nullable<System.DateTime> DAT_INICIAL_VIGENCIA { get; set; }
        public Nullable<System.DateTime> DAT_FINAL_VIGENCIA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SER_SERVICO> SER_SERVICO { get; set; }
    }
}
namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAC_RACA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RAC_RACA()
        {
            this.CRC_COR_RACA = new HashSet<CRC_COR_RACA>();
            this.NIN_NINHADA = new HashSet<NIN_NINHADA>();
            this.VAR_VARIEDADE_RACA = new HashSet<VAR_VARIEDADE_RACA>();
        }
    
        public int ISN_RACA { get; set; }
        public string DSC_RACA { get; set; }
        public Nullable<int> ISN_PARAMETRO { get; set; }
        public Nullable<int> CODIGO_RACA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRC_COR_RACA> CRC_COR_RACA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NIN_NINHADA> NIN_NINHADA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VAR_VARIEDADE_RACA> VAR_VARIEDADE_RACA { get; set; }
        public virtual PRD_PARAMETRO_DESCONTO PRD_PARAMETRO_DESCONTO { get; set; }
    }
}
namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class REG_REGIAO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REG_REGIAO()
        {
            this.CLB_CLUBE = new HashSet<CLB_CLUBE>();
            this.EST_ESTADO = new HashSet<EST_ESTADO>();
        }
    
        public int ISN_REGIAO { get; set; }
        public string DSC_REGIAO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLB_CLUBE> CLB_CLUBE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EST_ESTADO> EST_ESTADO { get; set; }
    }
}
namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class SER_SERVICO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SER_SERVICO()
        {
            this.SOL_SOLICITACAO = new HashSet<SOL_SOLICITACAO>();
        }
    
        public int ISN_SERVICO { get; set; }
        public string DSC_SERVICO { get; set; }
        public Nullable<int> ISN_PRECO_SERVICO { get; set; }
    
        public virtual PRS_PRECO_SERVICO PRS_PRECO_SERVICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOL_SOLICITACAO> SOL_SOLICITACAO { get; set; }
    }
}
namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOL_SOLICITACAO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOL_SOLICITACAO()
        {
            this.FAT_FATURA = new HashSet<FAT_FATURA>();
            this.CAR_CARRINHO = new HashSet<CAR_CARRINHO>();
            this.CUP_CUPOM = new HashSet<CUP_CUPOM>();
            this.ITF_ITEM_FATURA = new HashSet<ITF_ITEM_FATURA>();
        }
    
        public int ISN_SOLICITACAO { get; set; }
        public Nullable<int> ISN_SERVICO { get; set; }
        public Nullable<byte> STA_SOLICITACAO { get; set; }
        public string DSC_SOLICITACAO { get; set; }
        public Nullable<System.DateTime> DAT_SOLICITACAO { get; set; }
        public string DSC_OBSERVACAO { get; set; }
        public Nullable<int> ISN_PESSOA { get; set; }
        public Nullable<int> STA_PGTO { get; set; }
        public Nullable<int> ISN_TRANSFERENCIA { get; set; }
        public Nullable<int> ISN_NINHADA { get; set; }
    
        public virtual SER_SERVICO SER_SERVICO { get; set; }
        public virtual PES_PESSOA PES_PESSOA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAT_FATURA> FAT_FATURA { get; set; }
        public virtual NIN_NINHADA NIN_NINHADA { get; set; }
        public virtual TRA_TRANSFERENCIA TRA_TRANSFERENCIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAR_CARRINHO> CAR_CARRINHO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUP_CUPOM> CUP_CUPOM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITF_ITEM_FATURA> ITF_ITEM_FATURA { get; set; }
    }
}
namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRA_TRANSFERENCIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRA_TRANSFERENCIA()
        {
            this.ATR_ANEXO_TRANSFERENCIA = new HashSet<ATR_ANEXO_TRANSFERENCIA>();
            this.SOL_SOLICITACAO = new HashSet<SOL_SOLICITACAO>();
        }
    
        public int ISN_TRANSFERENCIA { get; set; }
        public string NOM_PROP_ORIGEM { get; set; }
        public string CPF_ORIGEM { get; set; }
        public string ENDERECO_ORIGEM { get; set; }
        public string NOM_PROP_DESTINO { get; set; }
        public string CPF_DESTINO { get; set; }
        public string ENDERECO_DESTINO { get; set; }
        public string NOM_CAO { get; set; }
        public string RG_CAO { get; set; }
        public string NUM_CEP_ORIGEM { get; set; }
        public string NUM_CEP_DESTINO { get; set; }
        public string DSC_COMPLEMENTO { get; set; }
        public string DSC_EMAIL { get; set; }
        public string DSC_COMPLEMENTO_DESTINO { get; set; }
        public string DSC_EMAIL_DESTINO { get; set; }
        public string BAIRRO_ORIGEM { get; set; }
        public string CIDADE_ORIGEM { get; set; }
        public string ESTADO_ORIGEM { get; set; }
        public string BAIRRO_DESTINO { get; set; }
        public string CIDADE_DESTINO { get; set; }
        public string ESTADO_DESTINO { get; set; }
        public string NOM_CO_PROPRIETARIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATR_ANEXO_TRANSFERENCIA> ATR_ANEXO_TRANSFERENCIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOL_SOLICITACAO> SOL_SOLICITACAO { get; set; }
    }
}
namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAR_VARIEDADE_RACA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VAR_VARIEDADE_RACA()
        {
            this.FIL_FILHOTE = new HashSet<FIL_FILHOTE>();
            this.CRC_COR_RACA = new HashSet<CRC_COR_RACA>();
        }
    
        public int ISN_VARIEDADE_RACA { get; set; }
        public string DSC_VARIEDADE { get; set; }
        public Nullable<int> ISN_RACA { get; set; }
        public Nullable<int> CODIGO_RACA { get; set; }
    
        public virtual RAC_RACA RAC_RACA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIL_FILHOTE> FIL_FILHOTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRC_COR_RACA> CRC_COR_RACA { get; set; }
    }
}
